### ISSUE TITLE
👀 Adding spec.generates.links to plugin (app & infra)

### ISSUE THREAD

**Issue by barbararochazup** [stack-spot/schemastore-stackspot#42]
```
#/studio-zup/plugin-grafana
meta:
  name: Plugin Grafana
spec:
  generates:
    link: 
      - name: Grafana Dev
        url: https://grafana.dev.zup.com.br/
        type: static
        picture: docs/grafana.png
```
